set_property SRC_FILE_INFO {cfile:C:/Users/thoma/EBER/GIT/EBER/simple-motor-2018.2/simple-motor.srcs/constrs_1/new/zybo_z720_constraints.xdc rfile:../../../simple-motor.srcs/constrs_1/new/zybo_z720_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W8    IOSTANDARD LVCMOS33     } [get_ports { uart_rtl_txd }]; #IO_L15N_T2_DQS_13 Sch=jb_n[1]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U7    IOSTANDARD LVCMOS33     } [get_ports { uart_rtl_rxd }]; #IO_L11P_T1_SRCC_13 Sch=jb_p[2]
